# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from nexum-api-client.models.position import Position
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LocationResponse(BaseModel):
    """
    LocationResponse
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    entity_id: Optional[StrictStr] = Field(default=None, description="Entity UUID")
    entity_type: Optional[StrictStr] = Field(default=None, description="Entity type")
    id: Optional[StrictStr] = Field(default=None, description="Location report ID")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional metadata")
    node_id: Optional[StrictStr] = Field(default=None, description="Node ID")
    position: Optional[Position] = None
    __properties: ClassVar[List[str]] = ["created_at", "entity_id", "entity_type", "id", "metadata", "node_id", "position"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LocationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "entity_id": obj.get("entity_id"),
            "entity_type": obj.get("entity_type"),
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "node_id": obj.get("node_id"),
            "position": Position.from_dict(obj.get("position")) if obj.get("position") is not None else None
        })
        return _obj


