# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr, field_validator
from pydantic import Field
from nexum-api-client.models.position import Position
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NearbyRequestSchema(BaseModel):
    """
    NearbyRequestSchema
    """ # noqa: E501
    center: Position
    entity_type: Optional[StrictStr] = Field(default=None, description="Filter by entity type (optional)")
    radius_km: Union[StrictFloat, StrictInt] = Field(description="Search radius in kilometers")
    __properties: ClassVar[List[str]] = ["center", "entity_type", "radius_km"]

    @field_validator('entity_type')
    def entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('responder', 'civilian', 'incident', 'resource', 'hazard'):
            raise ValueError("must be one of enum values ('responder', 'civilian', 'incident', 'resource', 'hazard')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NearbyRequestSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of center
        if self.center:
            _dict['center'] = self.center.to_dict()
        # set to None if entity_type (nullable) is None
        # and model_fields_set contains the field
        if self.entity_type is None and "entity_type" in self.model_fields_set:
            _dict['entity_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NearbyRequestSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "center": Position.from_dict(obj.get("center")) if obj.get("center") is not None else None,
            "entity_type": obj.get("entity_type"),
            "radius_km": obj.get("radius_km")
        })
        return _obj


