# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from nexum-api-client.models.location_response import LocationResponse
from nexum-api-client.models.position import Position
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NearbyResponseSchema(BaseModel):
    """
    NearbyResponseSchema
    """ # noqa: E501
    center: Optional[Position] = None
    count: Optional[StrictInt] = Field(default=None, description="Number of entities found")
    data: Optional[List[LocationResponse]] = Field(default=None, description="List of nearby locations")
    radius_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Search radius in kilometers")
    status: Optional[StrictStr] = Field(default=None, description="Response status")
    __properties: ClassVar[List[str]] = ["center", "count", "data", "radius_km", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NearbyResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of center
        if self.center:
            _dict['center'] = self.center.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NearbyResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "center": Position.from_dict(obj.get("center")) if obj.get("center") is not None else None,
            "count": obj.get("count"),
            "data": [LocationResponse.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None,
            "radius_km": obj.get("radius_km"),
            "status": obj.get("status")
        })
        return _obj


