# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.api_locations_history_entity_id_get400_response import ApiLocationsHistoryEntityIdGet400Response

class TestApiLocationsHistoryEntityIdGet400Response(unittest.TestCase):
    """ApiLocationsHistoryEntityIdGet400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiLocationsHistoryEntityIdGet400Response:
        """Test ApiLocationsHistoryEntityIdGet400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiLocationsHistoryEntityIdGet400Response`
        """
        model = ApiLocationsHistoryEntityIdGet400Response()
        if include_optional:
            return ApiLocationsHistoryEntityIdGet400Response(
                message = '',
                status = 'error'
            )
        else:
            return ApiLocationsHistoryEntityIdGet400Response(
        )
        """

    def testApiLocationsHistoryEntityIdGet400Response(self):
        """Test ApiLocationsHistoryEntityIdGet400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
