# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.nearby_request_schema import NearbyRequestSchema

class TestNearbyRequestSchema(unittest.TestCase):
    """NearbyRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NearbyRequestSchema:
        """Test NearbyRequestSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NearbyRequestSchema`
        """
        model = NearbyRequestSchema()
        if include_optional:
            return NearbyRequestSchema(
                center = nexum-api-client.models.position.Position(
                    accuracy = 10.0, 
                    alt = 100.0, 
                    lat = 52.52, 
                    lon = 13.405, ),
                entity_type = 'resource',
                radius_km = 5.0
            )
        else:
            return NearbyRequestSchema(
                center = nexum-api-client.models.position.Position(
                    accuracy = 10.0, 
                    alt = 100.0, 
                    lat = 52.52, 
                    lon = 13.405, ),
                radius_km = 5.0,
        )
        """

    def testNearbyRequestSchema(self):
        """Test NearbyRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
