# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nexum-api-client.api.locations_api import LocationsApi


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocationsApi()

    def tearDown(self) -> None:
        pass

    def test_api_locations_history_entity_id_get(self) -> None:
        """Test case for api_locations_history_entity_id_get

        Get location history for an entity
        """
        pass

    def test_api_locations_latest_get(self) -> None:
        """Test case for api_locations_latest_get

        Get latest location for each entity
        """
        pass

    def test_api_locations_nearby_post(self) -> None:
        """Test case for api_locations_nearby_post

        Find entities near a location
        """
        pass

    def test_api_locations_node_id_get(self) -> None:
        """Test case for api_locations_node_id_get

        Get current node ID
        """
        pass

    def test_api_locations_post(self) -> None:
        """Test case for api_locations_post

        Record a new location report
        """
        pass

    def test_api_locations_types_get(self) -> None:
        """Test case for api_locations_types_get

        Get list of valid entity types
        """
        pass


if __name__ == '__main__':
    unittest.main()
