# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.location_request_schema import LocationRequestSchema

class TestLocationRequestSchema(unittest.TestCase):
    """LocationRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationRequestSchema:
        """Test LocationRequestSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationRequestSchema`
        """
        model = LocationRequestSchema()
        if include_optional:
            return LocationRequestSchema(
                entity_id = '550e8400-e29b-41d4-a716-446655440000',
                entity_type = 'responder',
                metadata = {"name":"Team Alpha","status":"active"},
                node_id = 'node1',
                position = nexum-api-client.models.position.Position(
                    accuracy = 10.0, 
                    alt = 100.0, 
                    lat = 52.52, 
                    lon = 13.405, )
            )
        else:
            return LocationRequestSchema(
                entity_id = '550e8400-e29b-41d4-a716-446655440000',
                entity_type = 'responder',
                position = nexum-api-client.models.position.Position(
                    accuracy = 10.0, 
                    alt = 100.0, 
                    lat = 52.52, 
                    lon = 13.405, ),
        )
        """

    def testLocationRequestSchema(self):
        """Test LocationRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
