# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.node_id_response_schema import NodeIdResponseSchema

class TestNodeIdResponseSchema(unittest.TestCase):
    """NodeIdResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeIdResponseSchema:
        """Test NodeIdResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeIdResponseSchema`
        """
        model = NodeIdResponseSchema()
        if include_optional:
            return NodeIdResponseSchema(
                node_id = 'node-abc123',
                status = 'success'
            )
        else:
            return NodeIdResponseSchema(
        )
        """

    def testNodeIdResponseSchema(self):
        """Test NodeIdResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
