# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.entity_types_response_schema import EntityTypesResponseSchema

class TestEntityTypesResponseSchema(unittest.TestCase):
    """EntityTypesResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityTypesResponseSchema:
        """Test EntityTypesResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityTypesResponseSchema`
        """
        model = EntityTypesResponseSchema()
        if include_optional:
            return EntityTypesResponseSchema(
                data = ["responder","civilian","incident","resource","hazard"],
                status = 'success'
            )
        else:
            return EntityTypesResponseSchema(
        )
        """

    def testEntityTypesResponseSchema(self):
        """Test EntityTypesResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
