# coding: utf-8

"""
    Nexum Mesh API

    API for Nexum Mesh Network - Disaster Relief Communication System

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nexum-api-client.models.location_success_response_schema import LocationSuccessResponseSchema

class TestLocationSuccessResponseSchema(unittest.TestCase):
    """LocationSuccessResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationSuccessResponseSchema:
        """Test LocationSuccessResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationSuccessResponseSchema`
        """
        model = LocationSuccessResponseSchema()
        if include_optional:
            return LocationSuccessResponseSchema(
                data = nexum-api-client.models.location_response.LocationResponse(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    entity_id = '550e8400-e29b-41d4-a716-446655440000', 
                    entity_type = 'responder', 
                    id = 'loc-123', 
                    metadata = nexum-api-client.models.metadata.metadata(), 
                    node_id = 'node1', 
                    position = null, ),
                status = 'success'
            )
        else:
            return LocationSuccessResponseSchema(
        )
        """

    def testLocationSuccessResponseSchema(self):
        """Test LocationSuccessResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
